CHARACTER_LIMIT = 10000
ROW_LIMIT = 1000
WORKING_DIR = "data"

RAG_DATA_DIR = "data"
RAG_PERSIST_DIR = "code/.chroma"
RAG_COLLECTION_NAME = "support_kb"
RAG_EMBED_MODEL = "all-MiniLM-L6-v2"
RAG_TOP_K = 5
RAG_CHUNK_SIZE_CHARS = 1200
RAG_CHUNK_OVERLAP_CHARS = 150
