CHARACTER_LIMIT = 10000
ROW_LIMIT = 1000
WORKING_DIR = "data"

RAG_DATA_DIR = "data"
RAG_PERSIST_DIR = "code/.chroma"
RAG_COLLECTION_NAME = "support_kb"
RAG_EMBED_MODEL = "google/embeddinggemma-300m"
RAG_EMBED_QUERY_PREFIX = ""
RAG_EMBED_BATCH_SIZE = 4
RAG_TOP_K = 5
RAG_CHUNK_SIZE_CHARS = 1500
RAG_CHUNK_OVERLAP_CHARS = 150
